booking/urls.py
from django.urls import path
from booking import views

app_name = "booking"

urlpatterns = [
    path('check_room_availability',views.check_room_availability,name='check_room_availability'),
    path('add_to_selection/',views.add_to_selection,name='add_to_selection'),
    path('delete_selection/',views.delete_selection,name='delete_selection')
  
]

hms_prj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),


    path('user/',include('userauths.urls')),
    path('',include('hotel.urls')),
    path('ckeditor5/',include('django_ckeditor_5.urls')),
    path('booking/',include('booking.urls')),
    path('dashboard/',include('user_dashboard.urls'))

]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from . import views

app_name = "hotel"

urlpatterns = [
    path('',views.index,name='index'),
    path('detail/<slug>/',views.hotel_detail,name='hotel_detail'),
    path('detail/<slug:slug>/room-type/<slug:rt_slug>/',views.room_type_detail,name="room_type_detail"),
    path('selected_rooms/',views.selected_rooms,name='selected_rooms'),
    path('checkout/<booking_id>',views.checkout, name='checkout'),
    path('update_room_status/',views.update_room_status, name='update_room_status'),



    # Payment routes
    path('api/create_checkout_session/<booking_id>',views.create_checkout_session, name="api_checkout_session"),
    path('success/<booking_id>',views.payment_SUCCESS,name="success"),
    path('faild/<booking_id>',views.payment_faild, name= 'failed')



]

hotel/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import Hotel, Booking, ActivityLog, StaffOnDuty, Room, RoomType ,Coupon,Notification,Bookmark
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
import stripe 
from datetime import datetime
from django.urls import reverse
from django.http import JsonResponse
from decimal import Decimal
from django.utils import timezone



# Create your views here.


def index(request):
    hotels=Hotel.objects.filter(status='Live')
    context={
        'hotels':hotels
    }
    return render(request,'hotel/hotel.html',context)


def hotel_detail(request,slug):
    hotel=Hotel.objects.get(status='Live',slug=slug)

    if request.user.is_authenticated:
        bookmark = Bookmark.objects.filter(user=request.user, hotel=hotel)

    context={
        'hotel':hotel,
        'bookmark':bookmark
    }
    return render(request,'hotel/hotel_page.html',context)

def room_type_detail(request, slug,rt_slug):
    hotel =Hotel.objects.get(status='Live', slug=slug)
    room_type= RoomType.objects.get(hotel=hotel,slug=rt_slug)
    rooms= Room.objects.filter(room_type=room_type, is_available=True)

    id=request.GET.get('hotel-id')
    checkin=request.GET.get('checkin')
    checkout=request.GET.get('checkout')
    adutl=request.GET.get('adult')
    children=request.GET.get('children')






    print('id===',id)

    context={
        'hotel':hotel,
        'room_type':room_type,
        'rooms':rooms,
        'checkin':checkin,
        'checkout':checkout,
        'adult':adutl,
        'children':children

    }
    return render(request,'hotel/room_type_detail.html',context)


def selected_rooms(request):
    total=0
    room_count=0
    total_days=0
    adult=0
    children=0
    checkin=""
    checkout=""


    if 'selection_data_obj' in request.session:

        if request.method=='POST':
            for h_id,item in request.session['selection_data_obj'].items():
                id = int(item['hotel_id'])
                checkin = item['checkin']
                checkout = item['checkout']
                adult = int(item['adult'])
                children = int(item['children'])
                room_type_= int(item['room_type'])
                room_id = int(item['room_id'])

                user = request.user
                hotel = Hotel.objects.get(id=id)
                room= Room.objects.get(id=room_id)
                room_type= RoomType.objects.get(id=room_type_)

            date_format ="%Y-%m-%d"
            checkin_date= datetime.strptime(checkin,date_format)
            checkout_date = datetime.strptime(checkout,date_format)
            time_diffrence= checkout_date - checkin_date
            total_days_= time_diffrence.days
     

            full_name=request.POST['full_name']
            email=request.POST['email']
            phone=request.POST['phone']

            booking = Booking.objects.create(
                hotel=hotel,
                room_type=room_type,
                check_in_date=checkin,
                check_out_date=checkout,
                total_days=total_days_,
                num_adults=adult,
                num_children=children,
                full_name=full_name,
                email=email,
                phone=phone,
                user=request.user or None,
                payment_status="Processing"
            )

            # if request.user.is_authenticated:
            #     booking.user=request.user
            #     booking.save()
            # else:
            #     booking.user == None
            #     booking.save()

            for h_id,item in request.session['selection_data_obj'].items():
                room_id = int(item['room_id'])
                room = Room.objects.get(id=room_id)
                booking.room.add(room)

                room_count += 1
                days = total_days_
                price = room_type.price

                room_price = price * room_count
                total = room_price * days

            booking.total += float(total)
           
            booking.before_discount += float(total)
            booking.save()

            messages.success(request, "check out Now")

            return redirect('hotel:checkout',booking.booking_id)
            
           

            





        hotel = None
        for h_id,item in request.session['selection_data_obj'].items():
            id = int(item['hotel_id'])
            checkin = item['checkin']
            checkout = item['checkout']
            adult = int(item['adult'])
            children = int(item['children'])
            room_type= int(item['room_type'])
            room_id = int(item['room_id'])

            room_type = RoomType.objects.get(id=room_type)

            date_format ="%Y-%m-%d"
            checkin_date= datetime.strptime(checkin,date_format)
            checkout_date = datetime.strptime(checkout,date_format)
            time_diffrence= checkout_date - checkin_date
            total_days= time_diffrence.days

            room_count += 1
            days = total_days
            price = room_type.price

            room_price = price * room_count
            total = room_price * days


            hotel = Hotel.objects.get(id = id)
        
        context ={
            'data':request.session['selection_data_obj'],
            'total_selected_items':len(request.session['selection_data_obj']),
            'total':total,
            'total_days':total_days,
            'adult':adult,
            'children':children,
            'checkin':checkin,
            'checkout':checkout,
            'hotel':hotel


        }

        return render(request,'hotel/selected_rooms.html',context)

    else:
        messages.warning(request, 'no selected rooms yet')
        return redirect('/')
   


def checkout(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id)
    if request.method == "POST":

        code = request.POST.get('code')
        
        try:
            coupon = Coupon.objects.get(code__iexact=code, active= True)
            if coupon in booking.coupons.all():
                print('coupon is alredy taken')
                messages.warning(request,"Coupon already Activate")
                return redirect('hotel:checkout', booking.booking_id)
            else:
                if coupon.type == 'percentage':
                    discount = booking.total * coupon.discount / 100
                else:
                    discount = coupon.discount

                booking.coupons.add(coupon)
                booking.total -= discount
                booking.saved += discount
                booking.save()
                print("coupon is valid")
                messages.success(request, 'Coupon Activated')
                return redirect('hotel:checkout', booking.booking_id)
        except:
            print("coupon does not esists")
            messages.error(request,"Coupon doesn't exist")
            return redirect('hotel:checkout', booking.booking_id)


        
    
    context= {

        'booking':booking,
        'stripe_publishable_key':settings.STRIPE_PUBLIC_KEY,

    }
    return render(request,'hotel/checkout.html',context)




@csrf_exempt
def create_checkout_session(request,booking_id):
    booking = Booking.objects.get(booking_id= booking_id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    checkout_session = stripe.checkout.Session.create(
        customer_email= booking.email,
        payment_method_types=['card'],
        
        
        line_items=[
            {

                
                'price_data':{
                    'currency':'USD',
                    'product_data':{
                        'name':booking.full_clean
                    },
                    'unit_amount':int(booking.total*100)
                },
                'quantity':1
            }
        ],
        mode='payment',
        success_url=request.build_absolute_uri(reverse("hotel:success", args=[booking.booking_id])) + '?session_id{CHECKOUT_SESSION_ID}&success_id='+booking.success_id+'&booking_total='+str(booking.total),cancel_url=request.build_absolute_uri(reverse("hotel:failed", args=[booking.booking_id]))
    )

    booking.payment_status = 'Processing'
    booking.strip_payment_intent = checkout_session['id']
    booking.save()

    print('check session', checkout_session)
    return JsonResponse({'sessionId':checkout_session.id})

 
def payment_SUCCESS(request,booking_id):
    success_id = request.GET.get('success_id')
    booking_total = request.GET.get('booking_total')

    if success_id and booking_id:
        success_id = success_id.rstrip('/')
        booking_total = booking_total.rstrip('/')

        booking = Booking.objects.get(booking_id= booking_id,success_id=success_id)

        if booking.total == Decimal(booking_total):
            if booking.payment_status == "Processing":      
                booking.payment_status = "Paid"
                booking.is_active = True
                booking.save()

                noti= Notification.objects.create(
                    booking=booking,
                    type="Booking Confirmed",

                )
                if request.user.is_authenticated:
                    noti.user = request.user
                else:
                    noti.user = None
                noti.save()


                if 'selection_data_obj' in request.session:
                    del request.session['selection_data_obj']




            else:
                messages.success(request,"Payment made already, thanks for your patronage")
        else:
            messages.error(request,"hotel/payment_success.html")

    context={
        'booking':booking
    }

    return render(request,'hotel/payment_success.html',context)

def payment_faild(request,booking_id):
    return HttpResponse("Payment failed")

@csrf_exempt

templates/hotel/checkout.html
{% load static %}
{% include "base/base.html" %}

{% block content %}

<section>

</section>

<section>
    <div class="container-fluid mt-5 baseContainer">
        <div class="row">
            <div class="col-12 col-md-8 mb-4 ">
                <div class="container border p-4">
                    <h4><i class="fa-solid fa-bed  calender small m" ></i>&nbsp;Selected Rooms</h4>
                    <hr>
                    {% for r in booking.room.all  %}
                    <div class="container-fluid">
                        
                        <div class="row">
                            <div class="col-9">
                                <h5>Room: {{r.room_type.type}} <a style="cursor: pointer" class="delete-item ml-5 " data-item="{{id}}"><i class="fa-solid fa-trash text-danger"></i></a> </h5>
                              <small>Beds:{{r.room_type.number_of_beds}}</small> <br>
                              <small>Room Number:{{r.room_number}}</small>
                            </div>
                            <div class="col-3">
                                <button class="btn border">${{r.room_type.price}}</button>
                            </div>
                              
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                   
                </div>
                <div class="container border mt-5 p-4 ">
                    <h4 class="mt-4"><i class="fa-solid fa-user calender mr-2"></i> Billing Information</h4>
                    <hr>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <label for="First Name">First Name</label>
                        <input type="text" placeholder="First Name" name="full_name" class="form-control" value='{{booking.full_name}}' style='background: rgb(227,227,227)'>
                        <div class="row my-3">
                            <div class="col">
                                <label for="e-mail">E-Mail</label>
                              <input name="email" type="text" class="form-control" placeholder="First name" value='{{booking.email}}' style='background: rgb(227,227,227)'>
                            </div>
                            <div class="col">
                                <label for="Phone">Phone</label>
                              <input name="phone" type="text" class="form-control" placeholder="Last name" value='{{booking.phone}}' style='background: rgb(227,227,227)'>
                            </div>
                          </div>
                          <button class="btn nav_btn mb-3">Continue to checkout</button>
                    </form>
                    

                </div>
            </div>
            <div class="col-12 col-md-4 mb-4">
                <div class="container">
                    <div class="row imgss pt-5" style="background-image: url('{{booking.hotel.image.url}}');">

                        <div class="card-data text-left text-light mt-5 pt-5">
                            <h4>{{booking.hotel.name}}</h4>
                            <small><i class="fa-solid fa-location-dot colo pr-2"></i>&nbsp;&nbsp;{{booking.hotel.address}}</small>
                            <br>
                            <small><i class="fa-solid fa-phone colo pr-2 mr-1"></i>{{booking.hotel.mobile}}</small>
                          <div class="d-flex justify-content-between ">
                            <div class="ratings pl-4 pr-0">
                                <i class="fa fa-star rating-color"></i>
                                <i class="fa fa-star rating-color"></i>
                                <i class="fa fa-star rating-color"></i>
                                <i class="fa fa-star rating-color"></i>
                                <i class="fa fa-star"></i>
                            </div>
                           
                           </div>
                        </div>
                        
                    </div>
                    <div class="row border">
                        <h5 class="mt-4"><i class="fa-regular fa-calendar-days calender mr-2"></i>&nbsp;&nbsp;Booking Summary</h5>
                        
                        <div class="container-fluid">
                             <div class="row"><hr>
                                <div class="col-6">
                                    <p>Check-in</p>
                                    <p>Check-Out</p>
                                    <p>Total Days</P>
                                    
                                    <p>Adults</p>
                                    <p>Children</p>
                                    <p>Discount</p>
                                   
                                </div>
                                <div class="col-6">
                                    <p>{{booking.check_in_date}}</p>
                                    <p>{{booking.check_out_date}}</p>
                                    <P>{{booking.total_days}}Days</p>
                                    
                                    <p>{{booking.num_adults}} Adult</p>
                                    <p>{{booking.num_children}} Children</p>
                                    <p>-$ {{booking.saved}} </p>
                                   
                                </div>
                             </div>
                             <hr>
                             
                                <div class="container-fluid">
                                    <div class="row">
                                    <form  method="post">
                                            {% csrf_token %}
                                    
                                       
                                        <div class="col-8 m-0 p-0 ">
                                            <input type="text" class="form-control m-0 p-0 " id="coupenCode" name="code" placeholder=" Enter Your coupen Code">
                              
                                        </div>
                                        <div class="col-4 8 m-0 p-0 ">
                                            <button type="submit" class="btn btn-primary ">Apply</button>

                                        </div>
                                    </form>
                                    
                                    </div>
                                </div>
   
                                
                            

                              <hr>

                             <div class="row py-3">
                                <div class="col-6"><h5>Total Cost</h5></div>
                                <div class="col-6"><h5 class="colo">${{booking.total}}</h5></div>
                             </div>
                             <div id="paypal-button-container"></div>

                             <div class="container text-center">
                                <button style="background-color: rgb(193, 193, 21);" class="btn text-light btn-block"><strong class="mb-2 pt-0 mt-0">Pay with </strong><i class="fa-brands fa-2x fa-google-pay  ml-3"></i></button>
                                <button id="checkout-button"  class="btn nav_btn btn-block">Pay with striper <i class="fa-solid fa-credit-card my-2"></i> </button>

                             </div>



                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
















{% endblock content %}


{% block script %}
<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
<script src="https://js.stripe.com/v3/"></script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'scripts/custom.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<script>
    let booking_total="{{booking.total}}"
    let booking_id = "{{booking.booking_id}}"
    let success_id = "{{booking.success_id}}"
    paypal.Buttons({
        createOrder: function(date, actions){
            return actions.order.create({
               purchase_units: [{
                amount:{
                    value: booking_total                    
                }
               }]
            })
        },
        anApprove: function(data,actions){
            return actions.order.capture().then(function(Detail){
                console.log(Detail);
                if (Detail.status == "COMPLETED"){
                    // REDIRECT TO THE success page
                    window.location.href = `/success/${booking_id}/?success_id=${success_id}&payer_id=${Detail.id}&status=${Detail.status}&booking_total=${booking_total}`
                }
            });
        },
    })
    .render("#paypal-button-container")
</script>


<script>
    var stripe = Stripe('{{stripe_publishable_key}}')
    var checkoutButton = document.getElementById("checkout-button")

    checkoutButton.addEventListener('click',function(){
        var email ="{{booking.email}}"

        checkoutButton.innerHTML = "Processing <i class='fas fa-spinner fa-spin'></i>"

        fetch('/api/create_checkout_session/{{booking.booking_id}}',{
                method:"POST",
                body:JSON.stringify(
                    {email:email}
                )
            }).then(function(response){
                console.log(response)
                return response.json()
            })
            .then(function(session){
                return stripe.redirectToCheckout({sessionId:session.sessionId})
            }).then(function(result){
                if(result.error){
                    alert(result.error.message)
                }
            })
            .catch(function(error){
                console.log("Error: ",error)

            })



        console.log(email)
        console.log(stripe)
    })
</script>
{% endblock script %}

templates/hotel/hotel.html
{% load static %} {% include "base/base.html" %} {% block content %}

<section>
  <div class="backImg text-center text-white pt-5">
    <h2 class="mt-5">Book Unique Experiences</h2>
    <p>Discover top rated hotels,shops and resturants around the world</p>
    <div class="bg-light fm-group">
      <div class="input-group px-3">
        <input
          type="text"
          placeholder="Hotel, City.."
          class="form-control border-0 mt-2"
        />
        <input
          type="date"
          placeholder="Select Booking Date"
          class="form-control border-bottom-0 border-top-0 mt-2"
        />
        <input
          type="text"
          placeholder="All Categories"
          class="form-control mt-2 border-bottom-0 border-top-0 border-right-0"
        />

        <button class="btn btn-outline-secondary n_btn px-4 my-2" type="button">
          Search
        </button>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="text-center pt-5">
    <h3>Our Popular Tours</h3>
    <p>Explore the greates places in the City</p>

    <div class="container-fluid mb-5">
      <div class="row">

        {% for hotel in hotels %}
        <div class="col-md-6 col-lg-6 col-xl-4 my-5">
          <a href="{% url 'hotel:hotel_detail' hotel.slug  %}">
          <div class="card bg-dark text-white">
            <img class="card-img" src="{{hotel.image.url}}"
            alt="Card image">
            <div class="card-img-overlay">
              {% if hotel.featured == True %}
              <div style="position: absolute; left: 65%; "><h6 class="tags p-2 px-4">Featured</h6></div>
              {% endif %}
              
              <div class="card-data text-left">
                <h4>{{hotel.name}}</h4>
                <small
                  ><i class="fa-solid fa-location-dot pr-2"></i>{{hotel.address}} </small
                ><br />
                <small><i class="fa-solid fa-phone pr-2"></i>{{hotel.mobile}}</small>
              </div>
              <div class="bg-light text-dark mt-3 pt-3 mx-4 bottom-card">
                <div class="d-flex justify-content-between">
                  <div class="ratings pl-4 pr-0">
                    <i class="fa fa-star rating-color"></i>
                    <i class="fa fa-star rating-color"></i>
                    <i class="fa fa-star rating-color"></i>
                    <i class="fa fa-star rating-color"></i>
                    <i class="fa fa-star"></i>
                  </div><i class="fa-regular fa-eye"><small class="p-2">{{hotel.views}}</small></i>
                  <i class="fa-regular fa-heart pr-5 fa-xl pt-2"></i>
                </div>
              </div>
            </div>
          </div>
       
         </a>
        
        
        </div>

        {% endfor %}
      

       


      </div>
      
    </div>
  </div>
</section>
{% endblock content %}

templates/hotel/payment_success.html
{% load static %}
{% include "base/base.html" %}

{% block content %}

<section>
    <div class="container text-center mt-5">

        <img src="/static/imgs/success.webp" alt="" width="150px" class="mt-5">
        <h3>Checkout & Payment Successfull!</h3>
        <p>We have sent booking summary to <b>{{booking.email}}</b> and Your booking id is <b>{{booking.booking_id}}</b> Thank you.</p>
        <div class="container text-center">
            <div class="row">
                <div class="col-6">
                    <button class="btn btn-block nav_btn">Vist Dashbord</button>
                </div>
                <div class="col-6">
                    <button class="btn btn-block nav_btn">View Invoice</button>
                </div>
            </div>

        </div>
    </div>
</section>



{% endblock content %}


{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'scripts/custom.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


{% endblock script %}

templates/hotel/room_type_detail.html
{% extends "base/base.html" %} {% block content %}
{% load static%}
<div class="container text-center mt-5 pt-3">
  <h2>All Available Rooms</h2>
  <small>The {{room_type.type}}room has {{rooms.count}} availabe room(s)</small>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-12">
      <div class="container m-0 p-0">
        <div class="row d-flex justify-content-center ">
          {% for r in rooms %}

          <div class="col-4  border mt-5 mb-3  px-0">
            <div class="col-12 text-center nav_btn py-5 my-0">
              <h3>Room No.{{r.room_number}}</h3>
              <h5 class="d-inline">{{r.room_type.price}}$</h5>
              <small>/per Night</small>
            </div>
            <div class="col-12 text-center mt-5">
              <p>Bed:{{r.room_type.number_of_beds}}</p>
              <hr />
              <p>Room capacity:{{r.room_type.room_capacity}}</p>
              <hr />


              <div>

              <input type="text" class="room_id_{{r.id}} form-control" value="{{r.id}}" id='room_id' >
              <input type="text" class="room_number_{{r.id}} form-control" value="{{r.room_number}}" id="room_number">
              </div>


              <button class="btn nav_btn mb-4 mt-3 add-to-selection" data-index="{{r.id}}">
                add To <br />
                Selection
              </button>
            </div>
          </div>

          {% endfor %}

          <input class="form-control" type="text" value="{{hotel.id}}" id="id">
          <input class="form-control" type="text" value="{{hotel.name}}" id="hotel_name">
          <input class="form-control" type="text" value="{{room_type.type}}" id="room_name">
          <input class="form-control" type="text" value="{{room_type.price}}" id="room_price">
          <input class="form-control" type="text" value="{{room_type.number_of_beds}}" id="number_of_beds">
          <input class="form-control" type="text" value="{{room_type.id}}" id="room_type">
          <input class="form-control" type="text" value="{{checkin}}" id="checkin">
          <input class="form-control" type="text" value="{{checkout}}" id="checkout">
          <input class="form-control" type="text" value="{{adult}}" id="adult">
          <input class="form-control" type="text" value="{{children}}" id="children">



        </div>
      </div>
    </div>
    <div class="col-md-4 col-12">
      <div class="box-r my-3">
        <h5>
          <i class="fa-regular fa-calendar-days calender mr-2"></i
          ><b>Booking</b>
        </h5>
        <hr />
        <form class="" method="POST" action="{% url 'booking:check_room_availability' %}">
          {% csrf_token %}

          <!-- hotel_id -->
          <input type="hidden" id="" name="hotel-id" value="{{hotel.id}}">
        <label for="">Check-in date</label>
        <input type="date" name="checkin" class="form-control" >
        <label for="">Check-out Date</label>
        <input type="date" class="form-control" name="checkout" >
        <h6>Guests</h6>
       
        <label for="" class="text-center">Adults



        <div class="input-group inline-group ">
          <div class="input-group-prepend">
            <span class="btn btn-outline-secondary btn-minus">
              <i class="fa fa-minus"></i>
            </span>
          </div>
          <input class="form-control quantity" min="0" name="adult" value="1" type="number">
          <div class="input-group-append">
            <span class="btn btn-outline-secondary btn-plus">
              <i class="fa fa-plus"></i>
            </span>
          </div>
        </div>
      </label>
    


   
      <label for="" class="text-center">Children



      <div class="input-group inline-group  ">
        <div class="input-group-prepend">
          <span class="btn btn-outline-secondary btn-minus">
            <i class="fa fa-minus"></i>
          </span>
        </div>
        <input class="form-control quantity" min="0" name="children" value="1" type="number">
        <div class="input-group-append">
          <span class="btn btn-outline-secondary btn-plus">
            <i class="fa fa-plus"></i>
          </span>
        </div>
      </div></label>
    
  <br>

        <label for="">Select Room Typle</label>
        <br>
        <div class="select is-multiple">
        <select class="form-control" name='room_type' aria-label=".form-select-lg example">
          {% for r  in hotel.hotel_room_types  %}
          <option value='{{r.slug}}'>{{r.type}}</option>
          {% endfor %}
        </select>
        <br></div>
        <button class="btn nav_btn btn-block my-2">Check Availability</button>
        <div class="text-center">

        <button class="btn btn-wish text-enter"><i class="fa-regular fa-heart  fa-md px-2 "></i>Add to Wishlist</button>
         </div>

        </form>


      </div>

    </div>
  </div>
</div>

{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'scripts/custom.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<script>
 $('.btn-plus, .btn-minus').on('click', function(e) {
 const isNegative = $(e.target).closest('.btn-minus').is('.btn-minus');
 const input = $(e.target).closest('.input-group').find('input');
 if (input.is('input')) {
   input[0][isNegative ? 'stepDown' : 'stepUp']()
 }
})
</script>
{% endblock script %}