hms_prj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),


    path('user/',include('userauths.urls')),
    path('',include('hotel.urls')),
    path('ckeditor5/',include('django_ckeditor_5.urls')),
    path('booking/',include('booking.urls')),
    path('dashboard/',include('user_dashboard.urls'))

]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from . import views

app_name = "hotel"

urlpatterns = [
    path('',views.index,name='index'),
    path('detail/<slug>/',views.hotel_detail,name='hotel_detail'),
    path('detail/<slug:slug>/room-type/<slug:rt_slug>/',views.room_type_detail,name="room_type_detail"),
    path('selected_rooms/',views.selected_rooms,name='selected_rooms'),
    path('checkout/<booking_id>',views.checkout, name='checkout'),
    path('update_room_status/',views.update_room_status, name='update_room_status'),



    # Payment routes
    path('api/create_checkout_session/<booking_id>',views.create_checkout_session, name="api_checkout_session"),
    path('success/<booking_id>',views.payment_SUCCESS,name="success"),
    path('faild/<booking_id>',views.payment_faild, name= 'failed')



]

user_dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = "user_dashboard"


urlpatterns = [
    path("",views.dashboard, name="dashboard"),
    path('booking-detail/<booking_id>',views.booking_detail,name="booking_detail"),
    path('booking/',views.bookings,name="bookings"),
    path('notifications/',views.notifications,name="notifications"),
    path('notification_mark_as_seen/<id>',views.notification_mark_as_seen,name="notification_mark_as_seen"),
    path('wallet/',views.wallet,name="wallet"),
    path('bookmark/',views.bookmark,name="bookmark"),
    path('delete_bookmark/<bid>',views.delete_bookmark,name="delete_bookmark"),
    path('add_to_bookmark/',views.add_to_bookmark,name="add_to_bookmark"),
    path('profile/',views.profile,name="profile"),

    path("change-password/",auth_view.PasswordChangeView.as_view(template_name="user_dashboard/password-reset/change-password.html",success_url="/dashboard/password_changed"),name="change_password"),
    path('password_changed/',views.password_changed,name='password_changed')



]

userauths/urls.py
from django.urls import path
from . import views


app_name = "userauths"

urlpatterns = [
    path('sign-up',views.RegisterView,name="sign-up"),
    path('sign-in',views.loginViewTem,name="sign-in"),
    path('',views.logOut,name='logOut')

 
]

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>



      ``

  {% block link %}
  {% endblock link %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light">
        <a class="navbar-brand" href="#">earning</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "hotel:index" %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Hotels
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Accounts
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Blog</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pages
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
          </ul>
          
            <a href="{% url 'hotel:selected_rooms'%}" class="nav_btn btn mx-2  mx-0 my-sm-0" type="submit"><i class="fa-solid fa-bed pr-1" style="color: #ffffff;"></i>{{request.session.selection_data_obj|length}}</a>
          {% if request.user.is_authenticated %}
            <a href="{% url "user_dashboard:dashboard" %}" class="nav_btn btn mx-2  my-2 my-sm-0" type="submit">
              {% comment %} <i class="fa-solid fa-arrow-right-to-bracket pr-1" style="color: #ffffff;"></i> {% endcomment %}
              Dashboard</a>
            <a href="{% url "userauths:logOut" %}" class="nav_btn btn mx-2  my-2 my-sm-0" type="submit"><i class="fa-solid fa-power-off pr-1"></i>Sign Out</a>
          {% else %}
          <a href="{% url "userauths:sign-in" %}" class="nav_btn btn mx-2  my-2 my-sm-0" type="submit"><i class="fa-solid fa-arrow-right-to-bracket pr-1" style="color: #ffffff;"></i>Sign In</a>
          <a href="{% url "userauths:sign-up" %}" class="nav_btn btn mx-2  my-2 my-sm-0" type="submit"><i class="fa-solid fa-user-plus pr-1" style="color: #ffffff;"></i>Sign Up</a>

          {% endif %}
        </div>
      </nav>
      
      <script>
        {% for message in messages %}
          Swal.fire({
            icon:"{{ message.tags }}",
            title:"{{ message }}",
            text:"{{message.tags}}",
            timer: 1500
          });
        {% endfor %}
      </script>

    {% block content %}
    
    {% endblock content %}

  


    <!-- bootstrp javascript -->

    {% block script %}
    {% endblock script %}
   <!-- Full jQuery Library -->


   
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/75da3237a2.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/df8ea3872c.js" crossorigin="anonymous"></script>
</body>
</html>